### ISSUE TITLE
altyo doesn't compile

### ISSUE THREAD

**Issue by jaimemrjm** [ShyPixie/Overlays#2]
Hi,

altyo ebuild doesn't work for me. Portage shows a message about "valac not found". I think is because there are two valac installed in my Gentoo Linux: valac-0.26 and valac-0.30, so:
`local valac=$(find /usr/bin/valac-*)` makes a double string.

**Comment by calendulish** [comment]
It's fixed now.  I add the 0.4_rc18 version too.
